### ISSUE TITLE
[celery] Sentinel download must retry if data is offline

### ISSUE THREAD

**Issue by marujore** [brazil-data-cube/bdc-scripts#45]
Certain times Sentinel images are not online, but a download link is returned.
After request (up to 40 minutes) the image may be online.
#TODO: in download error check if download file is of size 0 and retry after 1 hour.

**Comment by raphaelrpl** [comment]
As mentioned in the issue duplicated #52, we must check for alternative cloud provider, such [Google Store Sentinel 2](https://cloud.google.com/storage/docs/public-datasets/sentinel-2)
